# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c212b6ce79e9586494aac5a4cacacb81cd15266bff2b0b659cb573ff2569620856874390f5fd06efbf2bbdc054a6cb7d19a99595ea87b25cb42bc74d4179652a

test:
  secret_key_base: 0f19eae561d4f459d9875ceb298f83663a07206e6ac7f3301993a3810165ddb03aab073a37640bd2735215288efcbaea813cfd9917050aaa7beabe8409a65379

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
